AWSTemplateFormatVersion: '2010-09-09'

Description: Parameter Store entries for the API keys of https://browse.ai


Resources:
  BrowseAiAPIKeyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/il-apr-comparator/browse-ai/api-key"
      Description: "API key for https://browse.ai. Consumed in application code."
      Type: String
      Value: "x"
      Tags:
        project: il-apr-comparator

  BrowseAiRobotIDParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/il-apr-comparator/browse-ai/robot-id"
      Description: "ID of the robot from https://browse.ai for scraping the Bake website. Consumed in application code."
      Type: String
      Value: "x"
      Tags:
        project: il-apr-comparator

  CoinPairsForIL:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/il-apr-comparator/bake/coin-pairs-for-il"
      Description: "List of coin pairs for which the impermanent losses get calculated. Consumed in application code."
      Type: StringList
      Value: "x"
      Tags:
        project: il-apr-comparator

  MailAddressForResultNotificationsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/il-apr-comparator/notifications/result/mail-address"
      Description: "Mail address to notify about the result of a comparator run. Consumed in other stack."
      Type: String
      Value: "x"
      Tags:
        project: il-apr-comparator

  MailAddressForErrorNotificationsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/il-apr-comparator/notifications/errors/mail-address"
      Description: "Mail address to notify about errors of a comparator run. Consumed in other stack."
      Type: String
      Value: "x"
      Tags:
        project: il-apr-comparator
