AWSTemplateFormatVersion: '2010-09-09'

Description: Lambda function to compare Impermanent Loss to APR.
# TODO: The application does not run in AWS because none of the scraping methods for the APR works inside Lambda!
# Check the corresponding source files for further information.


Parameters:
  ImageURI:
    Type: String
    Description: "URI of the container image (ECR repo) for the Lambda function."


Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Calculate Impermanent Loss for a given cryptocurrency coin pair and compare it to the APR from Liquidity Mining on Bake."
      Code:
        ImageUri: !Ref ImageURI
      PackageType: Image
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 600 # The browse.ai robot can run for quite some time
      Tags:
        - Key: "project"
          Value: "il-apr-comparator"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [!Ref AWS::Region, "il-apr-comparator-lambda-execution-role"]]
      Description: "Execution role automatically assumed by the corresponding Lambda function"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                "AWS:SourceAccount": !Sub "${AWS::AccountId}"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole # For access to CloudWatch
        - !Ref SNSPolicy
      Tags:
        - Key: "project"
          Value: "il-apr-comparator"

  SNSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allow publishing to the SNS topic for the il-apr-comparator"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
            - sns:publish
          Resource: !Ref SNSTopic

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: "project"
          Value: "il-apr-comparator"

  SNSTopicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/il-apr-comparator/sns/topic"
      Description: "Name of the SNS topic for notifications about the comparison result. Consumed in application code."
      Type: String
      Value: !Ref SNSTopic
      Tags:
        project: il-apr-comparator
