version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1


parameters:
  create-base-infrastructure:
    description: If true, creates the necessary base infrastructure in AWS.
    type: boolean
    default: false

  delete-stacks:
    description: If true, deletes the CloudFormation stacks in AWS.
    type: boolean
    default: false


jobs:
  deploy-ecr-repo:
    environment:
      AWS_REGION: eu-central-1
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            pip install -r ./aws/requirements.txt
      - aws-cli/setup:
          role-arn: arn:aws:iam::336250545151:role/OIDC-role-il-apr-comparator-eu-central-1
          aws-region: AWS_REGION
      - run:
          name: "Deploy stack for ECR"
          command: |
            ./aws/deploy_stack.py --template "./aws/ecr.yaml" --stack_name "il-apr-comparator-ecr-repo"

  lint-python-code:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./app/requirements.txt
      - run:
          name: "Install pylint"
          command: pip install pylint
      - run:
          name: "Lint code"
          command: make lint-python

  type-check-python-code:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./app/requirements.txt
      - run:
          name: "Install pyright"
          command: pip install pyright
      - run:
          name: "Check types"
          command: make typecheck-python

  lint-cloudformation-templates:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: "Install cfn-lint"
          command: pip install cfn-lint
      - run:
          name: "Lint code"
          command: make lint-cfn

  lint-dockerfile:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Install hadolint"
          command: |
            curl --location --output $HOME/bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64"
            chmod +x $HOME/bin/hadolint
      - run:
          name: "Lint Dockerfile"
          command: make hadolint

  build-image:
    docker:
      - image: cimg/base:2023.05
    steps:
      - checkout
      - run:
          name: "Build Docker image"
          command: make build

  upload-image:
    environment:
      AWS_REGION: eu-central-1
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: arn:aws:iam::336250545151:role/OIDC-role-il-apr-comparator-eu-central-1
          aws-region: AWS_REGION
      - run:
          name: "Upload image to ECR"
          command: |
            # TODO
            #commit_hash=$(git rev-parse HEAD)
            #docker tag $commit_hash $ecr_path:$commit_hash
            #docker push $ecr_path:latest
            #docker push $ecr_path:$commit_hash

  deploy-services:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./aws/requirements.txt
      - run:
          name: "Deploy stack for services"
          command: |
            # TODO
            #image_uri=...
            #./aws/deploy_stack.py --template "./aws/services.yaml" --parameters ImageURI=${image_uri} --stack_name "il-apr-comparator"

  delete-services:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./aws/requirements.txt
      - run:
          name: "Delete stack for services"
          command: ./aws/delete_stack.py --stack_name "il-apr-comparator"

  delete-ecr-repo:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./aws/requirements.txt
      - run:
          name: "Delete stack for services"
          command: ./aws/delete_stack.py --stack_name "il-apr-comparator-ecr-repo"


workflows:
  build-deploy:
    when:
      and:
        - not: << pipeline.parameters.create-base-infrastructure >>
        - not: << pipeline.parameters.delete-stacks >>
    jobs:
      - lint-python-code
      - type-check-python-code
      - lint-cloudformation-templates
      - lint-dockerfile
      - build-image:
          requires:
            - lint-python-code
            - type-check-python-code
            - lint-cloudformation-templates
            - lint-dockerfile
      - upload-image:
          requires:
            - build-image
      - deploy-services:
          requires:
            - upload-image

  create-base-infrastructure:
    when: << pipeline.parameters.create-base-infrastructure >>
    jobs:
      - deploy-ecr-repo

  delete-stacks:
    when: << pipeline.parameters.delete-stacks >>
    jobs:
      - delete-services
      - delete-ecr-repo:
          requires:
            - delete-services
