version: 2.1


parameters:
  create-base-infrastructure:
    description: If true, creates the necessary base infrastructure in AWS.
    type: boolean
    default: false

  delete-stacks:
    description: If true, deletes the CloudFormation stacks in AWS.
    type: boolean
    default: false


jobs:
  deploy-s3-buckets:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            pip install -r ./aws/requirements.txt
      - run:
          name: "Deploy stack for S3 buckets"
          command: |
            ./aws/deploy_stack.py --template "./aws/s3-buckets.yaml" --stack_name "il-apr-comparator-s3-lambda-buckets-stack"

  lint-python-code:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./scripts/requirements.txt
      - run:
          name: "Install pylint"
          command: pip install pylint
      - run:
          name: "Lint code"
          command: |
            for file in $(find . -name "*.py"); do
              echo "lint $file..."
              pylint $file
            done

  type-check-python-code:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./scripts/requirements.txt
      - run:
          name: "Install pyright"
          command: pip install pyright
      - run:
          name: "Check types"
          command: pyright

  lint-cloudformation-templates:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: "Install cfn-lint"
          command: pip install cfn-lint
      - run:
          name: "Lint code"
          command: |
            for file in $(find ./aws -name "*.yaml"); do
              echo "lint $file..."
              cfn-lint $file
            done

  deploy-dependencies:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install zip"
          command: |
            sudo apt-get update
            sudo apt-get install zip
      - run:
          # https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-package-with-dependency
          # https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-compile
          # https://chromedriver.chromium.org/getting-started
          # https://dev.to/awscommunity-asean/creating-an-api-that-runs-selenium-via-aws-lambda-3ck3
          name: "Install dependencies"
          command: |
            pip install -r ./scripts/requirements.txt --target ./dependencies/python

            #sudo apt-get install chromium-browser
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            #sudo apt-get install ./google-chrome-stable_current_amd64.deb
            dpkg-deb --instdir=./dependencies/bin

            curl -L https://chromedriver.storage.googleapis.com/112.0.5615.49/chromedriver_linux64.zip > chromedriver.zip
            unzip chromedriver.zip -d ./dependencies/bin
      - run:
          name: "Zip dependencies"
          command: |
            echo "export commit_hash=$(git rev-parse HEAD)" >> "$BASH_ENV"
            source "$BASH_ENV"
            cd ./dependencies
            zip -r ../dependencies-layer-commit-${commit_hash}.zip *
      - run:
          name: "Upload dependencies layer to S3"
          command: |
            source "$BASH_ENV"
            s3_bucket_name=$(aws ssm get-parameter --name "/il-apr-comparator/s3-bucket-lambda-layers/name" --query "Parameter.Value" --output text)
            aws s3 cp "dependencies-layer-commit-${commit_hash}.zip" "s3://$s3_bucket_name"

  deploy-code:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install zip"
          command: sudo apt-get install zip
      - run:
          # https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-package-with-dependency
          name: "Zip code"
          command: |
            echo "export commit_hash=$(git rev-parse HEAD)" >> "$BASH_ENV"
            source "$BASH_ENV"
            cd ./scripts
            zip -r ../deployment-package-commit-${commit_hash}.zip *
      - run:
          name: "Upload deployment package to S3"
          command: |
            source "$BASH_ENV"
            s3_bucket_name=$(aws ssm get-parameter --name "/il-apr-comparator/s3-bucket-lambda/name" --query "Parameter.Value" --output text)
            aws s3 cp "deployment-package-commit-${commit_hash}.zip" "s3://$s3_bucket_name"

  deploy-services:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./aws/requirements.txt
      - run:
          name: "Deploy stack for services"
          command: |
            commit_hash=$(git rev-parse HEAD)
            ./aws/deploy_stack.py --template "./aws/services.yaml" --parameters CommitHash=${commit_hash} --stack_name "il-apr-comparator-stack"

  delete-services:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./aws/requirements.txt
      - run:
          name: "Delete stack for services"
          command: ./aws/delete_stack.py --stack_name "il-apr-comparator-stack"

  delete-s3-buckets:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./aws/requirements.txt
      - run:
          name: "Empty S3 buckets"
          command: |
            lambda_bucket_name=$(aws ssm get-parameter --name "/il-apr-comparator/s3-bucket-lambda/name" --query "Parameter.Value" --output text)
            lambda_layers_bucket_name=$(aws ssm get-parameter --name "/il-apr-comparator/s3-bucket-lambda-layers/name" --query "Parameter.Value" --output text)
            aws s3 rm s3://$lambda_bucket_name --recursive
            aws s3 rm s3://$lambda_layers_bucket_name --recursive
      - run:
          name: "Delete stack for S3 buckets"
          command: |
            ./aws/delete_stack.py --stack_name "il-apr-comparator-s3-lambda-buckets-stack"


workflows:
  build-deploy:
    when:
      and:
        - not: << pipeline.parameters.create-base-infrastructure >>
        - not: << pipeline.parameters.delete-stacks >>
    jobs:
      - deploy-s3-buckets
      - lint-python-code
      - type-check-python-code
      - lint-cloudformation-templates
      - deploy-dependencies:
          requires:
            - deploy-s3-buckets
            - lint-python-code
            - type-check-python-code
            - lint-cloudformation-templates
      - deploy-code:
          requires:
            - deploy-s3-buckets
            - lint-python-code
            - type-check-python-code
            - lint-cloudformation-templates
      - deploy-services:
          requires:
            - deploy-dependencies
            - deploy-code

  create-base-infrastructure:
    when: << pipeline.parameters.create-base-infrastructure >>
    jobs:
      - deploy-s3-buckets

  delete-stacks:
    when: << pipeline.parameters.delete-stacks >>
    jobs:
      - delete-services
      - delete-s3-buckets:
          requires:
            - delete-services
