version: 2.1


parameters:
  create-base-infrastructure:
    description: If true, create the necessary base infrastructure in AWS.
    type: boolean
    default: false


jobs:
  lint-python-code:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./scripts/requirements.txt
      - run:
          name: "Install pylint"
          command: pip install pylint
      - run:
          name: "Lint code"
          command: |
            for file in $(find . -name "*.py"); do
              echo "lint $file..."
              pylint $file
            done

  type-check-python-code:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./scripts/requirements.txt
      - run:
          name: "Install pyright"
          command: pip install pyright
      - run:
          name: "Check types"
          command: pyright

  lint-cloudformation-templates:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run:
          name: "Install cfn-lint"
          command: pip install cfn-lint
      - run:
          name: "Lint code"
          command: |
            for file in $(find ./aws -name "*.yaml"); do
              echo "lint $file..."
              cfn-lint $file
            done

  deploy-to-lambda:
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - run:
          name: "Install zip"
          command: sudo apt-get install zip
      - run:
          name: "Zip code"
          command: zip -r deployment-package.zip ./scripts
      - run:
          name: "Empty S3 bucket"
          command: |
            s3_bucket_name=$(aws ssm get-parameter --name "/il-apr-comparator/s3-bucket-lambda/name" --query "Parameter.Value" --output text)
            aws s3 rm s3://$s3_bucket_name delete-content
      - run:
          name: "Upload code to S3"
          command: |
            s3_bucket_name=$(aws ssm get-parameter --name "/il-apr-comparator/s3-bucket-lambda/name" --query "Parameter.Value" --output text)
            aws s3 cp "deployment-package.zip" "s3://$s3_bucket_name"

  create-s3-bucket:
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            pip install -r ./aws/requirements.txt
            sudo apt-get install zip
      - run:
          name: "Create stack for S3 bucket"
          command: ./aws/create_stack.py --template "./aws/s3-lambda.yaml" --stack_name "il-apr-comparator-s3-bucket-stack"
      - run:
          name: "Zip code"
          command: zip -r deployment-package.zip ./scripts
      - run:
          name: "Upload code to S3"
          command: |
            s3_bucket_name=$(aws ssm get-parameter --name "/il-apr-comparator/s3-bucket-lambda/name" --query "Parameter.Value" --output text)
            aws s3 cp "deployment-package.zip" "s3://$s3_bucket_name"

  create-lambda-function:
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./aws/requirements.txt
      - run:
          name: "Create stack for Lambda function"
          command: ./aws/create_stack.py --template "./aws/lambda.yaml" --stack_name "il-apr-comparator-lambda-stack"

  create-ses:
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./aws/requirements.txt
      - run:
          name: "Create stack for SES"
          command: ./aws/create_stack.py --template "./aws/ses.yaml" --stack_name "il-apr-comparator-ses-stack"

  create-eventbridge:
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install -r ./aws/requirements.txt
      - run:
          name: "Create stack for EventBridge"
          command: ./aws/create_stack.py --template "./aws/eventbridge.yaml" --stack_name "il-apr-comparator-eventbridge-stack"


workflows:
  build-deploy:
    when:
      not: << pipeline.parameters.create-base-infrastructure >>
    jobs:
      - lint-python-code
      - type-check-python-code
      - lint-cloudformation-templates
      - deploy-to-lambda:
          requires:
            - lint-python-code
            - type-check-python-code
            - lint-cloudformation-templates
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\.[0-9]+\.?[0-9]+\.?[0-9]+/

  create-base-infrastructure:
    when: << pipeline.parameters.create-base-infrastructure >>
    jobs:
      - create-s3-bucket
      - create-lambda-function:
          requires:
            - create-s3-bucket
      #- create-ses
      #- create-eventbridge
