AWSTemplateFormatVersion: '2010-09-09'

Description: S3 buckets to store code and layers for Lambda function

Resources:
  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "il-apr-comparator-lambda-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: "project"
          Value: "il-apr-comparator"

  LambdaLayersBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "il-apr-comparator-lambda-layers-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: "project"
          Value: "il-apr-comparator"

  LambdaBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/il-apr-comparator/s3-bucket-lambda/name"
      Description: "Name of the S3 bucket which stores the deployment packages for the Lambda function. Param is consumed in the CircleCI pipeline."
      Type: String
      Value: !Ref LambdaBucket
      Tags:
        project: il-apr-comparator

  LambdaLayersBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/il-apr-comparator/s3-bucket-lambda-layers/name"
      Description: "Name of the S3 bucket which stores the packages for the Lambda Layers. Param is consumed in the CircleCI pipeline."
      Type: String
      Value: !Ref LambdaLayersBucket
      Tags:
        project: il-apr-comparator


Outputs:
  LambdaBucketName:
    Description: "Name"
    Value: !Ref LambdaBucket
    Export:
      Name: "il-apr-comparator:LambdaBucketName"

  LambdaLayersBucketName:
    Description: "Name"
    Value: !Ref LambdaLayersBucket
    Export:
      Name: "il-apr-comparator:LambdaLayersBucketName"
