AWSTemplateFormatVersion: '2010-09-09'

Description: Lambda function and other services to compare Impermanent Loss to APR.

# TODO: add eventbridge https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-run-lambda-schedule.html
# TODO: add ses

Parameters:
  ImageURI:
    Type: String
    Description: "URI of the container image (ECR repo) for the Lambda function."


Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Calculate Impermanent Loss for a given cryptocurrency coin pair and compare it to the APR from Liquidity Mining on CakeDefi."
      Code:
        ImageUri: !Ref ImageURI
      PackageType: Image
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 12
      Tags:
        - Key: "project"
          Value: "il-apr-comparator"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [!Ref AWS::Region, "il-apr-comparator-lambda-execution-role"]]
      Description: "Execution role automatically assumed by the corresponding Lambda function"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole # For access to CloudWatch
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
      Tags:
        - Key: "project"
          Value: "il-apr-comparator"
